//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommodityInfo
    {
        public int CommodityInfoId { get; set; }
        public int CommodityId { get; set; }
        public string Color { get; set; }
        public string Size { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Capacity { get; set; }
        public string ImageType { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual Commodity Commodity { get; set; }
    }
}
