//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public OrderDetail()
        {
            this.OrderCommodityDetails = new HashSet<CommodityInOrderDetail>();
        }
    
        public int OrderId { get; set; }
        public Nullable<double> Cost { get; set; }
    
        public virtual ICollection<CommodityInOrderDetail> OrderCommodityDetails { get; set; }
        public virtual Order Order { get; set; }
    }
}
