//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentCategory
    {
        public ParentCategory()
        {
            this.SubCategorys = new HashSet<SubCategory>();
        }
    
        public int ParentCategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<SubCategory> SubCategorys { get; set; }
    }
}
