//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoppingTrolley
    {
        public ShoppingTrolley()
        {
            this.CommodityInShoppingTrolleys = new HashSet<CommodityInShoppingTrolley>();
        }
    
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual ICollection<CommodityInShoppingTrolley> CommodityInShoppingTrolleys { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
