//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubCategory
    {
        public SubCategory()
        {
            this.Commoditys = new HashSet<Commodity>();
        }
    
        public int SubCategoryId { get; set; }
        public string CategoryName { get; set; }
        public int ParentCategoryId { get; set; }
    
        public virtual ParentCategory ParentCategory { get; set; }
        public virtual ICollection<Commodity> Commoditys { get; set; }
    }
}
