//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfileCommodity
    {
        public int UserId { get; set; }
        public int CommodityId { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual Commodity Commodity { get; set; }
    }
}
